apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 80
    nodePort: 30007 #optionnal
  - name: https
    protocol: TCP
    port: 9999
    targetPort: 443