apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 80
  clusterIP: 10.96.0.30
  type: ClusterIP
