kind: Service
apiVersion: v1
metadata:
  name: test-service-2
  namespace: default
spec:
  type: ExternalName
  externalName: test-service-1.namespace-1.svc.cluster.local
  ports:
  - port: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
spec:
  ports:
  - port: 443
  externalName: www.atomos.fr
  type: ExternalName


---

kind: Service
apiVersion: v1
metadata:
  name: external-service
  namespace: test
spec:
  type: ExternalName
  externalName: nginx.default.svc.cluster.local
  ports:
  - port: 8888