apiVersion: v1
kind: ServiceAccount
metadata:
  name: sderoche
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterRole1
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["describe"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRolebinding
metadata:
  name: clusterRoleBinding1
subjects:
- kind: ServiceAccount #can be User, Group
  name: sderoche #system:serviceaccounts:dev -> All SA in namespace "dev"
  namespace: default
roleRef:
  kind: ClusterRole
  name: clusterRole1
  apiGroup: rbac.authorization.k8s.io