apiVersion: v1
kind: LimitRange
metadata:
  name: test-lr
  namespace: test-lr
spec:
  limits:
  - default:
      memory: 100M
      cpu: 100m
    defaultRequest:
      memory: 50M
      cpu: 50m
    type: Container
    max:            #Acceptable max
      memory: 512M
      cpu: 500m
    min:            #Acceptable min
      memory: 50M
      cpu: 50m