apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: test-cm
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    envFrom: #Use all the CM as env
    - configMapRef:
        name: my-cm
    # env:
    # - name: KEY1
    #   valueFrom:
    #     configMapKeyRef:
    #       name: my-cm
    #       key: key1
    # - name: TEST
    #   valueFrom:
    #     configMapKeyRef:
    #       name: my-cm
    #       key: test

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: test-secret
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    envFrom: #Use all the Secret as env
    - secretRef:
        name: my-secret
    # env:
    # - name: USER
    #   valueFrom:
    #     configMapKeyRef:
    #       name: my-secret
    #       key: user
    # - name: PWD
    #   valueFrom:
    #     configMapKeyRef:
    #       name: my-secret
    #       key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: test-secret
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    # envFrom: #Use all the Secret as env
    # - secretRef:
    #     name: my-secret
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: user
    - name: PWD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password