apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-cm-volume
  volumes:
  - name: my-cm-volume
    configMap:
      name: cm-dir
      # items: # if this is not precised it will be a dir if you create a cm from multiple files
      # - key: multiple
      #   path: index.html

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-cm-volume
  volumes:
  - name: my-cm-volume
    configMap:
      name: my-cm
      items: # if this is not precised it will be a dir if you create a cm from multiple files
      - key: multiple
        path: index.html
      - key: key1
        path: test.html

--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-secret-volume
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret
      items: # if this is not precised it will be a dir if you create a cm from multiple files
      - key: user
        path: index.html
      - key: password
        path: test.html