apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-cm-volume
  volumes:
  - name: my-cm-volume
    configMap:
      name: cm-dir

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-secret-volume
      readOnly: true
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret
      defaultMode: 0644