# ATTACHED MODE
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  #   matchExpressions:
  #     - {key: environment, operator: In, values: [dev]}
  template: #Template of the pod
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx 