apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: prod
    app: front
spec:
  containers:
  - name: nginx
    image: nginx

---
# DETACHED MODE
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template: #Template of the pod
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx 