apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1G
    limits.cpu: 2
    limits.memory: 2G
    pods: 3

---

apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    resources:
      requests:
        cpu: 400m
        memory: 600M
      limits:
        cpu: 800m
        memory: 800M