apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8888
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-hp-volume
  volumes:
  - name: my-hp-volume
    hostPath:
      path: /tmp/testVolume
      type: DirectoryOrCreate