apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    # ports:
    # - containerPort: 8888
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-ed-volume
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    volumeMounts:
    - mountPath: /tmp/test
      name: my-ed-volume
  volumes:
  - name: my-ed-volume
    emptyDir: {}
      # medium: Memory  # <- RAM DISK