apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
    - image: nginx
      name: nginx
      volumeMount:
      - name: web
        mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
   name: web
 spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 200M

